### ISSUE TITLE
Icon missing in search bar

### ISSUE THREAD

**Issue by masonb-1** [uvera/firefox-extension-brave-search#6]
Minor issue: the Brave icon fails to load in the search bar on my system. The missing-icon icon also flickers each time I enter a new character. This issue was present directly following installation; there was no particular trigger.

![IMG_20240419_210326.jpg](https://github.com/uvera/firefox-extension-brave-search/assets/80439423/04681b19-9cae-43e1-8bb1-192692557de1)

Pop!_OS 22.04
Firefox 124.0.2 64-bit
Brave Search 1.2.0

**Comment by uvera** [comment]
Should be fixed in latest 1.3.0 version
